api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

default:
    resource: "@DefaultBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
